#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# mongodb-docker.sh
#
# Creates a MongoDB container for the Service Request Portal using Docker.
#
# It will:
#   - create a named volume so data survives container restarts
#   - start a `mongo` container with a root user
#   - on first start, run an init script that creates the application database
#     and a dedicated application user with readWrite on it
#
# Usage:
#   ./mongodb-docker.sh up        # create & start
#   ./mongodb-docker.sh down      # stop & remove container (volume kept)
#   ./mongodb-docker.sh purge     # stop, remove container AND volume (DATA LOSS)
#   ./mongodb-docker.sh logs      # tail logs
#   ./mongodb-docker.sh shell     # open mongosh inside the container
#   ./mongodb-docker.sh status    # show status
# -----------------------------------------------------------------------------
set -euo pipefail

CONTAINER_NAME="${CONTAINER_NAME:-sr-mongo}"
IMAGE="${IMAGE:-mongo:7}"
VOLUME_NAME="${VOLUME_NAME:-sr-mongo-data}"
INIT_VOLUME="${INIT_VOLUME:-sr-mongo-init}"
HOST_PORT="${HOST_PORT:-27017}"

ROOT_USER="${ROOT_USER:-root}"
ROOT_PASS="${ROOT_PASS:-rootpass-change-me}"

APP_DB="${APP_DB:-service_requests}"
APP_USER="${APP_USER:-srapp}"
APP_PASS="${APP_PASS:-srapp-pass}"

INIT_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)/mongo-init"

ensure_init_script() {
  mkdir -p "$INIT_SCRIPT_DIR"
  cat > "$INIT_SCRIPT_DIR/01-init-app-user.js" <<EOF
// Auto-generated by mongodb-docker.sh - runs on first container start.
// Creates the application DB, the application user, and the required indexes.
db = db.getSiblingDB("${APP_DB}");

// Create application user (idempotent)
try {
  db.createUser({
    user: "${APP_USER}",
    pwd: "${APP_PASS}",
    roles: [{ role: "readWrite", db: "${APP_DB}" }]
  });
  print("Created user ${APP_USER} on ${APP_DB}");
} catch (e) {
  print("User ${APP_USER} may already exist: " + e);
}

// Pre-create collections so the API doesn't have to on first boot
db.createCollection("serviceRequests");
db.createCollection("counters");

// Indexes
db.serviceRequests.createIndex({ caseNumber: 1 }, { unique: true, name: "uniq_caseNumber" });
db.serviceRequests.createIndex({ createdAt: -1 }, { name: "recent_first" });
db.serviceRequests.createIndex({ "customer.phone": 1 }, { name: "by_phone" });

print("Mongo init for ${APP_DB} complete.");
EOF
}

container_exists() {
  docker container inspect "$CONTAINER_NAME" >/dev/null 2>&1
}

cmd_up() {
  ensure_init_script

  docker volume inspect "$VOLUME_NAME" >/dev/null 2>&1 || docker volume create "$VOLUME_NAME" >/dev/null
  docker volume inspect "$INIT_VOLUME" >/dev/null 2>&1 || docker volume create "$INIT_VOLUME" >/dev/null

  # If a container with the name exists, refuse to overwrite - caller can use `down` first.
  if container_exists; then
    echo "Container '$CONTAINER_NAME' already exists. Use './mongodb-docker.sh down' first." >&2
    exit 1
  fi

  echo "Pulling $IMAGE ..."
  docker pull "$IMAGE"

  echo "Starting $CONTAINER_NAME on port $HOST_PORT ..."
  docker run -d \
    --name "$CONTAINER_NAME" \
    -p "${HOST_PORT}:27017" \
    -e MONGO_INITDB_ROOT_USERNAME="$ROOT_USER" \
    -e MONGO_INITDB_ROOT_PASSWORD="$ROOT_PASS" \
    -e MONGO_INITDB_DATABASE="$APP_DB" \
    -v "${VOLUME_NAME}:/data/db" \
    -v "${INIT_SCRIPT_DIR}:/docker-entrypoint-initdb.d:ro" \
    --health-cmd='mongosh --quiet --eval "db.adminCommand({ ping: 1 }).ok" || exit 1' \
    --health-interval=10s \
    --health-timeout=5s \
    --health-retries=10 \
    "$IMAGE" >/dev/null

  echo
  echo "MongoDB is starting. Connection strings:"
  echo "  Admin: mongodb://${ROOT_USER}:${ROOT_PASS}@localhost:${HOST_PORT}/admin"
  echo "  App:   mongodb://${APP_USER}:${APP_PASS}@localhost:${HOST_PORT}/${APP_DB}?authSource=${APP_DB}"
  echo
  echo "Tail logs with:  ./mongodb-docker.sh logs"
}

cmd_down() {
  if container_exists; then
    docker stop "$CONTAINER_NAME" >/dev/null || true
    docker rm "$CONTAINER_NAME" >/dev/null
    echo "Removed container '$CONTAINER_NAME'. Data volume '$VOLUME_NAME' retained."
  else
    echo "Container '$CONTAINER_NAME' does not exist."
  fi
}

cmd_purge() {
  cmd_down
  for v in "$VOLUME_NAME" "$INIT_VOLUME"; do
    if docker volume inspect "$v" >/dev/null 2>&1; then
      docker volume rm "$v" >/dev/null
      echo "Removed volume '$v'."
    fi
  done
}

cmd_logs() {
  docker logs -f "$CONTAINER_NAME"
}

cmd_shell() {
  docker exec -it "$CONTAINER_NAME" \
    mongosh "mongodb://${ROOT_USER}:${ROOT_PASS}@localhost:27017/admin"
}

cmd_status() {
  docker ps --filter "name=$CONTAINER_NAME" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
}

case "${1:-}" in
  up)     cmd_up ;;
  down)   cmd_down ;;
  purge)  cmd_purge ;;
  logs)   cmd_logs ;;
  shell)  cmd_shell ;;
  status) cmd_status ;;
  *)
    echo "Usage: $0 {up|down|purge|logs|shell|status}" >&2
    exit 2
    ;;
esac
